// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdjPAsl4Ow-NhkZ83SvkEnk10z5KGDGqs',
    appId: '1:1011267551240:web:4865adff7a10562ed951bd',
    messagingSenderId: '1011267551240',
    projectId: 'drtmodetest',
    authDomain: 'drtmodetest.firebaseapp.com',
    storageBucket: 'drtmodetest.appspot.com',
    measurementId: 'G-JHHHXY21J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClNTmxbxUvW9XciZh4-lcQmgZgOKxBLsI',
    appId: '1:1011267551240:android:841fab7ae908f6b8d951bd',
    messagingSenderId: '1011267551240',
    projectId: 'drtmodetest',
    storageBucket: 'drtmodetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYP4OpE-jlqTo0nNKhk4hah0cS0_xmZqU',
    appId: '1:1011267551240:ios:4fe6ca3354aafc65d951bd',
    messagingSenderId: '1011267551240',
    projectId: 'drtmodetest',
    storageBucket: 'drtmodetest.appspot.com',
    iosBundleId: 'com.example.diarraapp',
  );
}
